# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guitest1.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(861, 632)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AbilityScoreGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.AbilityScoreGroup.setGeometry(QtCore.QRect(40, 50, 201, 348))
        self.AbilityScoreGroup.setAcceptDrops(False)
        self.AbilityScoreGroup.setAutoFillBackground(False)
        self.AbilityScoreGroup.setFlat(False)
        self.AbilityScoreGroup.setCheckable(False)
        self.AbilityScoreGroup.setObjectName("AbilityScoreGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AbilityScoreGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.Label_AbilityScore = QtWidgets.QLabel(self.AbilityScoreGroup)
        self.Label_AbilityScore.setScaledContents(False)
        self.Label_AbilityScore.setObjectName("Label_AbilityScore")
        self.verticalLayout.addWidget(self.Label_AbilityScore)
        self.frame_StrengthMod = QtWidgets.QFrame(self.AbilityScoreGroup)
        self.frame_StrengthMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_StrengthMod.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_StrengthMod.setObjectName("frame_StrengthMod")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_StrengthMod)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SpinBox_StrengthScore = QtWidgets.QSpinBox(self.frame_StrengthMod)
        self.SpinBox_StrengthScore.setMinimumSize(QtCore.QSize(80, 0))
        self.SpinBox_StrengthScore.setMinimum(8)
        self.SpinBox_StrengthScore.setMaximum(20)
        self.SpinBox_StrengthScore.setObjectName("SpinBox_StrengthScore")
        self.horizontalLayout_2.addWidget(self.SpinBox_StrengthScore)
        self.label_StrengthScore = QtWidgets.QLabel(self.frame_StrengthMod)
        self.label_StrengthScore.setObjectName("label_StrengthScore")
        self.horizontalLayout_2.addWidget(self.label_StrengthScore)
        self.label_EchoStrengthMod = QtWidgets.QLabel(self.frame_StrengthMod)
        self.label_EchoStrengthMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EchoStrengthMod.setObjectName("label_EchoStrengthMod")
        self.horizontalLayout_2.addWidget(self.label_EchoStrengthMod)
        self.verticalLayout.addWidget(self.frame_StrengthMod)
        self.frame_DextMod = QtWidgets.QFrame(self.AbilityScoreGroup)
        self.frame_DextMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DextMod.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_DextMod.setObjectName("frame_DextMod")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_DextMod)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SpinBox_DextScore = QtWidgets.QSpinBox(self.frame_DextMod)
        self.SpinBox_DextScore.setMinimumSize(QtCore.QSize(80, 0))
        self.SpinBox_DextScore.setMinimum(8)
        self.SpinBox_DextScore.setMaximum(20)
        self.SpinBox_DextScore.setObjectName("SpinBox_DextScore")
        self.horizontalLayout_3.addWidget(self.SpinBox_DextScore)
        self.label_DextScore = QtWidgets.QLabel(self.frame_DextMod)
        self.label_DextScore.setObjectName("label_DextScore")
        self.horizontalLayout_3.addWidget(self.label_DextScore)
        self.label_EchoDextMod = QtWidgets.QLabel(self.frame_DextMod)
        self.label_EchoDextMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EchoDextMod.setObjectName("label_EchoDextMod")
        self.horizontalLayout_3.addWidget(self.label_EchoDextMod)
        self.verticalLayout.addWidget(self.frame_DextMod)
        self.frame_ConstMod = QtWidgets.QFrame(self.AbilityScoreGroup)
        self.frame_ConstMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ConstMod.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ConstMod.setObjectName("frame_ConstMod")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_ConstMod)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SpinBox_ConstScore = QtWidgets.QSpinBox(self.frame_ConstMod)
        self.SpinBox_ConstScore.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_ConstScore.sizePolicy().hasHeightForWidth())
        self.SpinBox_ConstScore.setSizePolicy(sizePolicy)
        self.SpinBox_ConstScore.setMinimumSize(QtCore.QSize(80, 0))
        self.SpinBox_ConstScore.setMinimum(8)
        self.SpinBox_ConstScore.setMaximum(20)
        self.SpinBox_ConstScore.setObjectName("SpinBox_ConstScore")
        self.horizontalLayout.addWidget(self.SpinBox_ConstScore)
        self.label_ConstScore = QtWidgets.QLabel(self.frame_ConstMod)
        self.label_ConstScore.setObjectName("label_ConstScore")
        self.horizontalLayout.addWidget(self.label_ConstScore)
        self.label_EchoConstMod = QtWidgets.QLabel(self.frame_ConstMod)
        self.label_EchoConstMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EchoConstMod.setObjectName("label_EchoConstMod")
        self.horizontalLayout.addWidget(self.label_EchoConstMod)
        self.verticalLayout.addWidget(self.frame_ConstMod)
        self.frame_IntelMod = QtWidgets.QFrame(self.AbilityScoreGroup)
        self.frame_IntelMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_IntelMod.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_IntelMod.setObjectName("frame_IntelMod")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_IntelMod)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SpinBox_IntelScore = QtWidgets.QSpinBox(self.frame_IntelMod)
        self.SpinBox_IntelScore.setMinimumSize(QtCore.QSize(80, 0))
        self.SpinBox_IntelScore.setMinimum(8)
        self.SpinBox_IntelScore.setMaximum(20)
        self.SpinBox_IntelScore.setObjectName("SpinBox_IntelScore")
        self.horizontalLayout_4.addWidget(self.SpinBox_IntelScore)
        self.label_IntelScore = QtWidgets.QLabel(self.frame_IntelMod)
        self.label_IntelScore.setObjectName("label_IntelScore")
        self.horizontalLayout_4.addWidget(self.label_IntelScore)
        self.label_EchoIntelScore = QtWidgets.QLabel(self.frame_IntelMod)
        self.label_EchoIntelScore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EchoIntelScore.setObjectName("label_EchoIntelScore")
        self.horizontalLayout_4.addWidget(self.label_EchoIntelScore)
        self.verticalLayout.addWidget(self.frame_IntelMod)
        self.frame_WisdomMod = QtWidgets.QFrame(self.AbilityScoreGroup)
        self.frame_WisdomMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_WisdomMod.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_WisdomMod.setObjectName("frame_WisdomMod")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_WisdomMod)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SpinBox_WisdomScore = QtWidgets.QSpinBox(self.frame_WisdomMod)
        self.SpinBox_WisdomScore.setMinimumSize(QtCore.QSize(80, 0))
        self.SpinBox_WisdomScore.setMinimum(8)
        self.SpinBox_WisdomScore.setMaximum(20)
        self.SpinBox_WisdomScore.setObjectName("SpinBox_WisdomScore")
        self.horizontalLayout_5.addWidget(self.SpinBox_WisdomScore)
        self.label_WisdomScore = QtWidgets.QLabel(self.frame_WisdomMod)
        self.label_WisdomScore.setObjectName("label_WisdomScore")
        self.horizontalLayout_5.addWidget(self.label_WisdomScore)
        self.label_EchoWisdomMod = QtWidgets.QLabel(self.frame_WisdomMod)
        self.label_EchoWisdomMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EchoWisdomMod.setObjectName("label_EchoWisdomMod")
        self.horizontalLayout_5.addWidget(self.label_EchoWisdomMod)
        self.verticalLayout.addWidget(self.frame_WisdomMod)
        self.frame_CharismaMod = QtWidgets.QFrame(self.AbilityScoreGroup)
        self.frame_CharismaMod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CharismaMod.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_CharismaMod.setObjectName("frame_CharismaMod")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_CharismaMod)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SpinBox_CharismaScore = QtWidgets.QSpinBox(self.frame_CharismaMod)
        self.SpinBox_CharismaScore.setMinimumSize(QtCore.QSize(80, 0))
        self.SpinBox_CharismaScore.setMinimum(8)
        self.SpinBox_CharismaScore.setMaximum(20)
        self.SpinBox_CharismaScore.setObjectName("SpinBox_CharismaScore")
        self.horizontalLayout_6.addWidget(self.SpinBox_CharismaScore)
        self.label_CharismaScore = QtWidgets.QLabel(self.frame_CharismaMod)
        self.label_CharismaScore.setObjectName("label_CharismaScore")
        self.horizontalLayout_6.addWidget(self.label_CharismaScore)
        self.label_EchoCharismaMod = QtWidgets.QLabel(self.frame_CharismaMod)
        self.label_EchoCharismaMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EchoCharismaMod.setObjectName("label_EchoCharismaMod")
        self.horizontalLayout_6.addWidget(self.label_EchoCharismaMod)
        self.verticalLayout.addWidget(self.frame_CharismaMod)
        self.frame_CharismaMod.raise_()
        self.frame_StrengthMod.raise_()
        self.frame_ConstMod.raise_()
        self.frame_IntelMod.raise_()
        self.frame_WisdomMod.raise_()
        self.frame_DextMod.raise_()
        self.Label_AbilityScore.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_open_file = QtWidgets.QAction(MainWindow)
        self.action_open_file.setObjectName("action_open_file")
        self.actionSpeichern = QtWidgets.QAction(MainWindow)
        self.actionSpeichern.setObjectName("actionSpeichern")
        self.actionSpeichern_unter = QtWidgets.QAction(MainWindow)
        self.actionSpeichern_unter.setObjectName("actionSpeichern_unter")
        self.menuDatei.addAction(self.action_new)
        self.menuDatei.addAction(self.action_open_file)
        self.menuDatei.addAction(self.actionSpeichern)
        self.menuDatei.addAction(self.actionSpeichern_unter)
        self.menubar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AbilityScoreGroup.setTitle(_translate("MainWindow", "Ability Scores/Modifiers"))
        self.Label_AbilityScore.setText(_translate("MainWindow", "Ability Score Points: 27"))
        self.label_StrengthScore.setText(_translate("MainWindow", "Strength"))
        self.label_EchoStrengthMod.setText(_translate("MainWindow", "-1"))
        self.label_DextScore.setText(_translate("MainWindow", "Dexterity"))
        self.label_EchoDextMod.setText(_translate("MainWindow", "-1"))
        self.label_ConstScore.setText(_translate("MainWindow", "Constitution"))
        self.label_EchoConstMod.setText(_translate("MainWindow", "-1"))
        self.label_IntelScore.setText(_translate("MainWindow", "Intelligence"))
        self.label_EchoIntelScore.setText(_translate("MainWindow", "-1"))
        self.label_WisdomScore.setText(_translate("MainWindow", "Wisdom"))
        self.label_EchoWisdomMod.setText(_translate("MainWindow", "-1"))
        self.label_CharismaScore.setText(_translate("MainWindow", "Charisma"))
        self.label_EchoCharismaMod.setText(_translate("MainWindow", "-1"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.action_new.setText(_translate("MainWindow", "Neu"))
        self.action_new.setToolTip(_translate("MainWindow", "Neuen Char erstellen"))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_open_file.setText(_translate("MainWindow", "Öffnen"))
        self.action_open_file.setToolTip(_translate("MainWindow", "Bestehende Datei Öffnen"))
        self.action_open_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSpeichern.setText(_translate("MainWindow", "Speichern"))
        self.actionSpeichern.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSpeichern_unter.setText(_translate("MainWindow", "Speichern unter"))
        self.actionSpeichern_unter.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))

